[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yenwealth"
version = "0.4.1"
description = "Financial planning tools for individuals living in Japan"
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "arch",
    "beartype",
    "numpy",
    "pandas",
    "pydantic",
    "returns"
]

[project.optional-dependencies]
dev = [
    "icecream",
    "pycodestyle",
    "pyright",
    "pytest",
    "ruff"
]

[tool.ruff]
line-length = 120
