[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yenwealth"
version = "0.1.0"
description = "Financial planning tools for individuals living in Japan"
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "beartype"
]

[project.optional-dependencies]
dev = [
    "pycodestyle",
    "pytest",
]
